### ISSUE TITLE
Plugin factory (idea)

### ISSUE THREAD

**Issue by iksi** [getkirby-v2/kirby#181]
I’m running in to some trouble that might occur more often as more Kirby plugins arrive. Currently most plugins create a global helper function to access the plugin. As I’m working on a Twitter plugin right now, in ran into the existing global function `twitter()` that is in the `kirby/helpers.php` file. I’d like a way to prevent running into such a problem and also be able to clearly see from a template that it is a plugin that is being called instead of a global kirby function. And keeping it syntactically nice as well.

The idea is to create some sort of ‘plugin factory’ method that only looks inside the plugin folder and returns an instance for that plugin which can be accessed from templates as follows:

``` PHP
<?php foreach(plugin('twitter')->timeline('username')->statuses() as $status): ?>
<?php endforeach ?>
```

**Comment by lukasbestle** [comment]
The problem is that plugins are implemented in very different ways. Some expose a function, some a class, some don't even define any public functions but do stuff internally (like adding a route etc.).

The idea of a helper function combined with a convention of how plugins that support it should look like is a great idea. Maybe, it could be as easy as "the `plugin('twitter')` function tries to create an instance of the `TwitterPlugin` class or, if that fails, throws an Exception", as plugins get loaded automatically anyway and the function would only need to create an instance of that already loaded class.
Plugins that don't define that class would have to be used like before.
