### ISSUE TITLE
Repository friendly folder structure

### ISSUE THREAD

**Issue by dionysiusmarquis** [getkirby-v2/kirby#312]
Hi,

I know this may change quite a lot to the core of Kirby, but the content order handling using `1- ... 2-` isn't very repository friendly. When two people are working inside the projects content for example and one is changing the order while another is still changing things, you are getting

```
1-project-a
1-project-b
2-project-a
2-project-b
```

quite easily. It's already doable when you are using the panel and a `structure field`. Maybe that's something that could find it's way to the core as a option to save the order in the corresponding `.txt` rather than in the folder name, like it's done for files already too.

What do you think?

**Comment by lukasbestle** [comment]
Generally your version control system should be able to detect such changes as rename operations. Merging conflicted changes is difficult, but it has always been. ;)

I don't think we should change this behavior or implement two different solutions (they will collide if you use both at the same time), because the current structure makes it very easy to see the order in the file system.

**Comment by dionysiusmarquis** [comment]
In my experience it may produce unnecessary possible conflicts and in some circumstances confusing repository history. And some how it just feels strange to get 100+ commit changes by doing such trivial thing as a content order change :smiley:

**Comment by lukasbestle** [comment]
I have been using Kirby with Git for quite some time now and have never felt like this is especially annoying. But that's definitely subjective. :)

What you could do is to ignore visibility in your template code completely. Instead, you can create a field with a custom sorting value and then sort in your templates using `$pages->sortBy('field')`. This would be a custom replacement of what you wrote you wanted in the core.

**Comment by dionysiusmarquis** [comment]
Yeah, I'm doing it with ``structures`` to sort and proceed just pages used in a structure as a workaround. Working fine as well.

**Comment by laszlokorte** [comment]
Not a version control problem but one caused by the folder structure as well:

Images and other files get uploaded into the content folder. The generated URLs ($file->url()) points to the file in the content folder directly instead of getting routed through the same mechanism as the pages.

This results in all file urls being changed when the the order of the pages changes or a page is made visible/invisible.

I just sent a newsletter for which I had prepared a special landing page (in kirby). Into the newsletter I embedded an image which was uploaded as file into the landing page. I had marked the landing page as invisible until the newsletter was sent. Then when I published the landing page the URL of the image changed and all the URLs in the already sent email became invalid.

I suggest the file urls should be dispatched the same way as the page urls (ignoring the order/date prefix of the folders)

**Comment by texnixe** [comment]
@laszlokorte : I agree absolutely. 

To solve your current problem, you could use a router to redirect to the new image urls.

**Comment by laszlokorte** [comment]
@texnixe Thank you. The current problem already has been solved by a rewrite rule in the htaccess.
I just put the story there to provide a real usecase I encountered yesterday.

**Comment by lukasbestle** [comment]
Kirby redirects file URLs relative to the page URL to the actual file system URL now. I have wrote about it in [the Forum](https://forum.getkirby.com/t/get-the-seo-url-for-images-from-kirby-api/232/6?u=lukasbestle).

**Comment by laszlokorte** [comment]
@lukasbestle Thank you. That's good to know and helpful in my situation. 

Nevertheless you explicitly mention that it is not recommended, an extra redirect is involved and I have to do a manual string concatenation.
I rather would like to see "non-changing file urls" being the standard behavior when using the `$file->url()` API and not causing a redirect.

I assume the reason for the current behavior is to avoid pushing large files through the php interpreter just to pass them to the webserver (?)

**Comment by lukasbestle** [comment]
That's exactly the reason. Webservers can serve files way better than PHP. Also it works basically everywhere, even if URL rewriting is not possible (the actual paths will always work).
