### ISSUE TITLE
Route with the pattern just `(:all)` does not match

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/kirby#368]
See [this post](https://forum.getkirby.com/t/routes-prevent-nesting-from-hell/3304/4?u=lukasbestle).

I have debugged this a bit. The Router replaces the placeholder correctly and the resulting string is `#^(.*)$#u`. It is the same if I manually use the pattern `(.*)`, but it doesn't match when using the placeholder.

This is most likely not a Toolkit issue since the replacing works. But what is happening then?

**Comment by distantnative** [comment]
I think it's caused by this fallback route from the core which already claims `(:all)` as route: https://github.com/getkirby/kirby/blob/master/kirby.php#L372-L406

And looking at it, it seems to have been implemented but never really finished in what it should achieve.

But yea, looks to me that the `run()` method from the router rather gets this one than any custom one from the `config.php`.

**Comment by lukasbestle** [comment]
That totally makes sense!

**Comment by bastianallgeier** [comment]
Kirby 2 has reached its end of life and will no longer be actively supported by us. We recommend to upgrade to Kirby 3: https://github.com/getkirby
