### ISSUE TITLE
$page->show() function

### ISSUE THREAD

**Issue by Pascalmh** [getkirby-v2/kirby#399]
There is a Solution how to do the opposite of `$page->hide()` [in the Forum](https://forum.getkirby.com/t/page-hide-reversed-function/410/7) but I still think it would be nice to have it as a function on its own.

**Comment by lukasbestle** [comment]
Well, it's difficult. There is now an [option](https://getkirby.com/docs/panel/blueprints/subpages-settings#numbering-of-subpages) to change the numbering to use `0` or the date. Since the core doesn't know anything about blueprints, the user would need to pass that option to the `show()` method so that it knows what to do.

**Comment by Pascalmh** [comment]
Default would be `1..n` - if you used `date` or `0` you have to pass a parameter - `$page->show($sorting = 'numeric')` - that would make it a lot easier then the solution in the Forum.

**Comment by lukasbestle** [comment]
Yes, I thought about something like that as well.
