### ISSUE TITLE
Page URL cannot use Japanese

### ISSUE THREAD

**Issue by ghost** [getkirby-v2/kirby#491]
When you create a page (not from the panel) with a URL containing Japanese characters, trying to view that page in a browser results in a 404. If you open a web inspector, you can see that the GET request for the page has URL encoded the Japanese text in the URL (e.g. %E3%83%86%E3%82%B9%E3%83%88) which is not decoded by Kirby to route to the appropriate page.

Related to that, when creating a page in the panel, typing in a Japanese title does not automatically fill in the “URL-prefix” field. And when you manually input Japanese text there, that text is erased/rejected when you try to save or click outside of the field.

**Comment by lukasbestle** [comment]
Kirby's page UIDs/URIs are currently not intended to be compatible with UTF-8 characters. Many web proxies, caches and other web infrastructure don't fully support non-ASCII URLs, so it's recommended to use ASCII only.

I have marked this as an idea/feature request.

**Comment by stephenbenedict** [comment]
Ah, I did not know that. Thanks.

**Comment by fvsch** [comment]
But there is no such thing as non-ASCII URLs, since path text is restricted to a subset of ASCII (excluding characters such as U+0020 SPACE, U+0025 PERCENT SIGN and U+0028 LEFT PARENTHESIS for instance), and all other characters are URL-encoded. Similarly, domain names are restricted a different subset of ASCII and offer a different encoding mechanism for other characters (punycode).

This means that a well-formed URL *is* ASCII (and actually stricter than just ASCII), so I’m not sure why web proxies and caches would choke on them. Are they known to check on paths containing URL-encoding sequences (e.g. `%20` for a space)? URL encoding is used extensively by popular web sites such as Wikipedia. Random example: [巴西皇太子阿方索](https://zh.wikipedia.org/wiki/%E5%B7%B4%E8%A5%BF%E7%9A%87%E5%A4%AA%E5%AD%90%E9%98%BF%E6%96%B9%E7%B4%A2).

I think that the actual challenge would be on the filesystem. Having a content folder named `1.巴西皇太子阿方索` reliably on Windows, macOS and different flavors of Linux hosting, letting users deploy this using FTP without errors… this might very well work seamlessly nowadays, or it might be a can of worms.

But while I understand that the Panel may stick to generating restricted slugs for folder names (and thus URLs), I do think that if Kirby gets a path with URL-encoded chars it should decode it and try to match a corresponding folder. Being conservative in what you output but a bit more liberal in what input you can work with.

**Comment by lukasbestle** [comment]
I fully agree that it would be great if it just worked out of the box with Kirby.
You are right that URLs use URL encoding, but I have had problems with UTF-8 characters in URLs before, even if properly encoded.

As I wrote above, I consider this as a feature request.
