### ISSUE TITLE
Return field objects for user data (especially user structure fields)

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#524]
Not sure if this is more of a feature than a bug, but trying to use the `yaml()` or `structure()` methods on a structure field in a user file results in an error:

https://forum.getkirby.com/t/structure-field-type-not-working-properly-on-user-fields/2838/9

```
$user->some_structure_field()
```
returns an array.

**Comment by lukasbestle** [comment]
A structure is not a page but a collection, so it doesn't return field objects. I agree that fields would sometimes be great, but currently it's sort of a feature.

**Comment by texnixe** [comment]
I know that a structure is not a page. Maybe this is a misunderstanding?

```
gettype($page->structurefield())
```
returns "object".

```
gettype($user->structurefield())
```
returns "array"

**Comment by lukasbestle** [comment]
Please see my edit. :)

**Comment by texnixe** [comment]
Yep, I understand that, I posted this, because it is misleading for the user, because he has learned to use `yaml()` or `toStructure()` on a structure field and if he does the same with a structure field in the user file, he get's an error. At least, we would have to explain it in the docs, if we don't want to change the behavior.

**Comment by lukasbestle** [comment]
Yes, that's definitely true. I'm on the side of fixing this, but we need to check the consequences first.

**Comment by LeBenLeBen** [comment]
Any update regarding this topic? I tried to add a custom field method that I could use on a field I added to my users, but the field method return a string instead of a field which prevents me to call my method on it.

I was trying to do that because I cannot add methods directly on users, which would be a awesome feature. For example you could create things like `$user->fullName()` or more complex functions that takes basic user user informations to generate more complex data.
