### ISSUE TITLE
Registering plugin language files

### ISSUE THREAD

**Issue by mzur** [getkirby-v2/kirby#532]
Plugins should be able to register their own language files through the extension registry (as described [here](https://forum.getkirby.com/t/plugin-developers-how-do-you-load-language-files/6218)). It might look like this:
```php
// site/plugins/myplugin/myplugin.php
$kirby->set('translation', 'de', __DIR__.'/languages/de.php');
```
Both PHP and YAML language files should be supported. Kirby will then defer loading of the correct file until the actual language of the page is detected by the router.

**Comment by lukasbestle** [comment]
Kirby should also load the registered files first so that the site language files can override language variables.

**Comment by lord-executor** [comment]
I am reasonably familiar with the code of registries and the part of the code that currently loads the translation files. I have also some interest in a solution that doesn't require weird workarounds in my plugin implementations, so I could have a go at an implementation of this and create a pull request if you think this would be helpful.

**Comment by lord-executor** [comment]
Interesting... Github detects issue links across all repositories. Just to be clear: this does not have anything to do with this issue directly, except that I'll have to revisit my implementation once it is resolved.

**Comment by lukasbestle** [comment]
You can definitely send a PR, but please note that merging PRs isn't necessarily faster for us than writing the code ourselves, especially for larger changes like this one (we need to verify and test the new code).

Which means: A PR for larger features is great to have an intermediary Kirby version to test with and to use until the changes are merged, but it probably won't be in a release quicker.

**Comment by lord-executor** [comment]
@lukasbestle That's what I figured. Quality control of software is hard enough even without adding the open source factor ;)

I'll see what I can do and maybe if I add some good unit tests and documentation, it'll end up saving at least a little bit of time.

**Comment by jenstornell** [comment]
So we should register all the languages we have? Like this?

```php
$kirby->set('translation', 'de', __DIR__.'/languages/de.php');
$kirby->set('translation', 'sv', __DIR__.'/languages/sv.php');
$kirby->set('translation', 'en', __DIR__.'/languages/en.php');
```

A few questions comes to mind.

## At least 4 ways to detect the current language

How should Kirby figure out the currently used language? I think there are at least four different ways to do that.

### 1. Browser language

In [one of my plugins](https://github.com/jenstornell/splitview/blob/master/core/language-switcher.php) I use the browser language to detect the current language. That option works good on the frontend when multi language setup is not used.

### 2. Panel user language

In another plugin (can't remember which one) I used the panel user language to figure out the current language. This works best in the panel for example in a field.

### 3. Language option

In [a plugin](https://github.com/texnixe/kirby-logger/blob/master/lib/helpers.php#L61) by @texnixe an option is used to find out the language to use. In some case this might be the best way.

### 4. Multi language code

In a multi language setup a language are selected on the frontend. Maybe a plugin need to use this language code to work good.

### How is it solved?

How do we deal with this? Should Kirby figure it out? Or should plugin developers build an own language detector?

If the plugin developer should create an own detector, I don't see a meaning in register all the languages, because only one will be used. Maybe that's the idea of it, that only one should be registered?

## Suggestion

I don't know if it's a good one but here are a suggestion that could solve the above.

### Browser detect language

```php
$kirby->set('translation/browser', 'en', __DIR__.'/languages/en.php');
```

### Panel user detect language

```php
$kirby->set('translation/user', 'en', __DIR__.'/languages/en.php');
```

### Translation option

```php
$kirby->set('translation/option', 'plugin.my_plugin.en', __DIR__.'/languages/en.php');
```

### Multi language detect language

```php
$kirby->set('translation/multilanguage', 'en', __DIR__.'/languages/en.php');
```

## Fallback to default

If a language is somehow detected and it does not exist, how should it know what language to fall back to? Maybe english is a good language, but should that always be default?

**Comment by lukasbestle** [comment]
> If the plugin developer should create an own detector, I don't see a meaning in register all the languages, because only one will be used. Maybe that's the idea of it, that only one should be registered?

No. Then we wouldn't need a registry and everything would be like it is now. Plugins should register all language files they have and Kirby will select one.
We should definitely not introduce several different ways of registering languages like you proposed. There should only be one way, otherwise all plugins would select their language files differently.

The detected language always needs to be the current language in multilang. If we start to detect this differently, parts of the page will be in one language and parts will be in another language.

There are several conclusions from this:

- For installations without multilang support (just a single language) we need a global config option (for all plugins together!) that defines the language to use, it can't be detected here.
- While we are at it, this option can be used to load the respective language file from `site/languages`. Currently those files are only loaded for multilang sites.
- The different language files of a plugin need to be set in one go so that Kirby can load the default one if the correct language doesn't exist. (probably English, but maybe we should make the global config option from the first conclusion support an array of languages that is used as a list of priorities). Setting in one go would mean a syntax like this:
  
  ```php
  $kirby->set('translations', ['de' => __DIR__.'/languages/de.php', 'en' => __DIR__.'/languages/en.php']);
  ```

**Comment by mzur** [comment]
Point 1: That's exactly what I'm doing with Uniform, too. I'd welcome a config option that works for all plugins.

Point 2: Do you mean loading the language file from `site/languages` _in addition_ to the language files of the plugins?

Point 3: I chose the `$kirby->set` call with three arguments to be consistent with all the other [available extensions](https://getkirby.com/docs/developer-guide/plugins/registry). But it makes sense to register all language files in one go. Maybe this can be a general improvement of the `set` call, e.g. for registering multiple templates:
```php
$kirby->set('template', [
   'blog' => __DIR__ . '/templates/blog.php',
   'article' => __DIR__ . '/templates/article.php',
]);
```
However, this doesn't work for multiple aliases of a single entity like this:
```php
$kirby->set('blueprint', ['article.text', 'article.video'], __DIR__ . '/blueprints/article.yml');
```

**Comment by lukasbestle** [comment]
Point 2: Yes. This will allow users to override the translations from plugins, even in single-language setups where the custom files are currently not loaded.

Point 3: There are other registries with only two arguments like the `route` registry. I don't think we should introduce an artificial second param just to make it three params. Regarding registering multiple templates etc.: Maybe in the future, but I think this increases complexity quite a bit when there are so many different ways to call the set method.

**Comment by samnabi** [comment]
Why are we using the `translation` keyword here, instead of `language`?

`$kirby->set('template', ...)` gets overriden by `site/templates`, so it seems inconsistent that `$kirby->set('translation', ...)` would get overriden by `site/languages`.

**Comment by jenstornell** [comment]
## Frontend

Good points @lukasbestle.

**Point 1:** For single language sites on the frontend I agree that a global option would be the best for all plugins to use.
**Point 2:** I also agree that it would be nice to load built in translation from the choosen language when the global option is used.

### Point 3:

I'm not sure about the array. I often prefer single lines because of readability.

If we still really need an array, I agree with @mzur that we probably expect other `set` calls to support it as well.

But to not complicate things, maybe go with an option for it:

```php
c::set('language.default', 'en'); // Could be set as default by Kirby if not in options.php
```

`language` instead of `translation` sounds good @samnabi.

**In conclusion for the frontend:** It seems like we all agree on point 1 and 2. The third one is a bit more debatable.

## Panel

It can be easy to think that what is working for the frontend would work just as fine in the Panel, but it does not and I will tell you why.

### The Panel is using the user language

Download langkit and go to the panel. Look at the translations of the Panel while changing language. It's still english no matter what language you select. That's because the Panel is not using the multi language translations, it's using the user language.

### Plugin fields and the rest of the Panel should be translated the same way

Let's say I have created a plugin that is adding a field to the panel. Let's say I also add translations for this field.

If the translation of my field/widget would change when I change the multi language in the panel, it would be really inconsistant to the rest of the Panel. The multi language selector is to edit a page on a specific language, not to change translation of the panel. That's what user language is for.

To make it clear what I mean (if I'm not clear enough) I add an animated gif which shows that selecting another multi language does not change the Panel language, because it's set by the user. The fields/widgets etc should use the user language as well.

***I pretend I'm a German in this test***

![panel-user-language](https://cloud.githubusercontent.com/assets/927011/21759848/bf7e4a80-d647-11e6-88ca-7183971454da.gif)

### Solution

The really simple solution for it should probably be to just check if the panel is loaded and if it is, always use the user language. That way we can still have a single `set` that works the same way for all plugins.

**Comment by texnixe** [comment]
I absolutely agree with @jenstornell regarding Panel plugins.

**Comment by mzur** [comment]
@jenstornell @texnixe This shouldn't affect the way plugin developers register their language files, though, should it? Kirby/The Panel is responsible for selecting the correct language files and we only need to tell it where to find them and not what to load (when).

**Comment by texnixe** [comment]
@mzur Yes, of course.

**Comment by lukasbestle** [comment]
**Point 3**: We will need an array here, the language files of one plugins need to be registered together. Otherwise Kirby won't be able to select a fallback in case the preferred language is not available in that plugin (which is not too uncommon!).
And just that we have an array here doesn't mean that other registries should support it as well. The route registry takes an array as well, which just comes from the route data structure. I think we should keep the registries separate regarding their data structure and features.

Regarding the **Panel**: That's a very good point! I agree that we should just select languages differently inside the Panel. Plugins aren't supposed to contain any kind of selection logic, so this is the best way. Only issue are fallbacks again. What to do if a plugin doesn't have the current user language available?

Another point regarding the Panel: We will definitely need to load the custom language files inside the Panel as well (based on the user language again), otherwise users won't be able to override plugin translations for Panel plugins. The language files are currently not loaded inside the Panel as far as I know.

**Comment by jenstornell** [comment]
### Point 3

Maybe I'm a bit stubborn, but I still don't get why an array is needed. Is it because it would not be able to separate my registered plugin languages from other registerered plugin languages?

It would probably be possible to figure out which belongs where by using the folder path as a kind of id and group by that.

**An example, se comment:**

```php
// Plugin 1
$kirby->set('translation', 'de', __DIR__.'/languages/de.php'); // plugin-1/languages/
$kirby->set('translation', 'sv', __DIR__.'/languages/sv.php'); // plugin-1/languages/

// Plugin 2
$kirby->set('translation', 'de', __DIR__.'/languages/en.php'); // plugin-2/languages/
$kirby->set('translation', 'sv', __DIR__.'/languages/en.php'); // plugin-2/languages/
$kirby->set('translation', 'en', __DIR__.'/languages/en.php'); // plugin-2/languages/
```

The only pitfall I see is that I can't scatter my language files all over the place in my plugin folder structure, because then it would be impossible to group them correctly.

Or does this solution contains too much magic?

### Set arguments

I don't have a clear opinion about the `set` arguments but when I developed Kirby Bricks I thought it was nice that most of the `set` calls looks the same. Then I could reduce my code quite a bit: https://github.com/jenstornell/kirby-bricks/blob/master/set-file.php

But I understand the reasons for having different arguments as well. My suggestion is simple, keep it the same as long as possible and if it needs to break, break it.

### Panel

>What to do if a plugin doesn't have the current user language available?

Good question. I'm starting to think that it may be the plugin developer who should somehow set a fallback language. Or if the language does not exists, always fall back to the first registered language of that plugin.

**Comment by lukasbestle** [comment]
> Or does this solution contains too much magic?

Yes, it does. Never use magic when explicit syntax can be used. That explicit syntax is an array in this case. But: We could also just register the language *directory* instead and make Kirby get the list of languages dynamically from that. This doesn't require any magic either.

> My suggestion is simple, keep it the same as long as possible and if it needs to break, break it.

I agree! :)

> I'm starting to think that it may be the plugin developer who should somehow set a fallback language. Or if the language does not exists, always fall back to the first registered language of that plugin.

Hm, I think fallback languages should always be something that is set by the user as they depend on the languages that the user actually understands. The plugin dev doesn't know that.

A simple fix would be to hardcode English as fallback language and require plugins to always have an English language file. This would improve consistency and reduce complexity with multiple installed plugins. Of course hardcoding isn't entirely optimal.

**Comment by jenstornell** [comment]
>We could also just register the language directory instead and make Kirby get the list of languages dynamically from that.

That would be brilliant! I vote for that. Then plugin developers does not need to update the `set` call every time a new language is added.

>I think fallback languages should always be something that is set by the user

Yes, but if the user wants `sv` and the plugin only have `de` and `dk`, what should it pick?

>A simple fix would be to hardcode English as fallback

I could live with that. I think that `en` will dominate the world a few lifetimes anyway.

Now we are in a great direction I think. I don't have anything more to add. Feels great! =)

**Comment by texnixe** [comment]
> Yes, but if the user wants sv and the plugin only have de and dk, what should it pick?

That's the point. Therefore forcing plugin devs to provide an English language file and enforcing English as a fallback probably makes sense.

**Comment by jenstornell** [comment]
@texnixe Yes and I agree with that. =)

**Comment by lukasbestle** [comment]
It's awesome how much discussion there can (and needs to) be for one seemingly simple feature. It shows that stuff like this is quite complex.

Thank you all for your great input!
