### ISSUE TITLE
Idea: choose urls with/without trailing slash

### ISSUE THREAD

**Issue by iksi** [getkirby-v2/kirby#545]
Kirby by default creates urls without a trailing slash like: http://www.example.com/about
For the sake of making it easier to migrate existing sites to Kirby that might use trailing slashes an option to have urls end with a trailing slash would be a nice to have.

````PHP
c::option('url.trailing_slash', true);
````

This would result in having http://www.example.com/about/
I’d be more than happy to make a pull request for this.

**Comment by sebsel** [comment]
Note that at this moment, http://www.example.com/about///// is also possible. Would be nice if this fixes that too.

**Comment by bastianallgeier** [comment]
Sounds like a great option, but also like a lot of places to watch if this will cause issues.

**Comment by jenstornell** [comment]
How is this going to work?

Currently both these version works to visit:

```text
example.com/about
example.com/about/
```

So when setting this this option, should `/about` without slash still work? If it's going to work just like Kirby is working now it would only affect the urls generated by the Kirby functions, for example:

```php
echo $page->url();
```

It means no redirect from `/about` to `/about/` but instead links goes to `/about/` instead of `/about`.

If someone think it's better to force a redirect from `/about` to `/about/`, think about this. If it's a migration from WordPress or another CMS, all users have always visited `/about/` and not `/about`. Therefor I think `/about` should return the page with 200 like today, no redirect OR error 404, but not a redirect.

A redirect 301 says a url has moved from `/about` to `/about/` but with a migration like this it has not. It's always been on `/about/`.

So in general I think redirect 301 should only be used when a page has really been moved and not an automated magic. A really bad think with WordPress was that it often tried to guess redirect pages when they was renamed/moved/etc. It ended up with a soup of endless redirect chains and after a while there was no control over the redirects any more. That's why I'm a bit afraid of going that road.

If it does not include automatic redirects I think it's a good idea.

**Comment by sebsel** [comment]
It might be slightly unrelated, but <https://getkirby.com/docs///////////> is a thing. It's a 200 now, and that is a bit weird.

**Comment by jenstornell** [comment]
@sebsel I agree that it's not very nice. I think it should return error 404. But the question in that case is when:

```text
 https://getkirby.com/docs/
 https://getkirby.com/docs//
```

Should the first version still work with a single ending slash? For me personally I've used that the first version with a single slash works for migrations from WordPress. Then I just changed the urls to something like this:

```php
<a href="<?php echo $page->url(); ?>/">Page</a>
```

And for the case about I think it would be nice with this option this issue is all about.

**Comment by lukasbestle** [comment]
I agree with you on the "never use 301 for this" part, permanent redirects can lead to all sorts of issues like redirection loops if the configuration changes. But: I think we should redirect with 302 here. Keeping the old URLs working doesn't make any sense.

**Comment by iksi** [comment]
Agree on leaving permanent redirects out of this. The fact that multiple slashes work in urls is that filesystems don’t seem to give any special meaning to them and resolve to the same document as an url with single slashes. Static html websites also ‘tolerate’ the multiple slashes. I’ve only seen some nginx servers rewrite multiple slashes in the url to single ones. All in all I don’t think this is something Kirby should ‘solve’.

**Comment by fvsch** [comment]
> Agree on leaving permanent redirects out of this.

+1. Or any redirects, really. Redirects are tricky. I have a few on my own Kirby-powered website (for redirecting to trailing-slash URLs, and for redirecting away from "draft" content), and from time to time when I change a comma or a bit of server config I end up in redirection loops. :P

An option that makes `Page::url` output URLs ending with a trailing slash would be great. I could clean up my templates a bit.

**Comment by fvsch** [comment]
Due to some issues with serving static HTML pages (https://github.com/fvsch/kirby-staticbuilder/issues/29), static builds with StaticBuilder may end up *requiring* trailing slashes for all HTML pages. Having this natively in Kirby would be helpful.
