### ISSUE TITLE
trigger a hook pre and post of panel event

### ISSUE THREAD

**Issue by bnomei** [getkirby-v2/kirby#563]
currently hooks seem to trigger post all their work is done.
https://getkirby.com/docs/developer-guide/advanced/hooks

maybe it could be extended like kirbytext per and post filters to support both. with post as default?
https://getkirby.com/docs/developer-guide/kirbytext/filters

example:
```php
kirby()->hook(['panel.page.delete', 'panel.page.delete@post'], function($page) {
  // same, same
  // wanted to do backup zip of $page folder but it is gone already.
  // ‎(ﾉಥ益ಥ）ﾉ ┻━┻
});

kirby()->hook('panel.page.delete@pre', function($page) {
  // awesome – now i can do a backup before folder enters binary-nirvana. 
  // ( ⁼̴̤̆ ළ̉ ⁼̴̤̆)و ̑̑
});
```

**Comment by jenstornell** [comment]
I like the idea, but not the syntax.

**Comment by bnomei** [comment]
seperate `pre-delete` and `post-delete` events then?

**Comment by jenstornell** [comment]
About the naming I think it should have been:

```text
panel.page.delete
panel.page.deleted
```

In this case `delete` is before and `deleted` is after.

Now we already have `delete` as the after hook, so if we made it to this it would be a breaking change. Anyway it would probably not break much because the delete hook would still run on delete, but a bit earlier.

**Comment by texnixe** [comment]
> Anyway it would probably not break much because the delete hook would still run on delete, but a bit earlier.

That might make a big difference, depending on when exactly the pre-delete event is called.

As regards the naming, I think your suggested names are too close and therefore error prone.

**Comment by bnomei** [comment]
maybe take inspiration from [jquery ajax](https://api.jquery.com/jQuery.ajax/) and call it `beforeDelete`?

**Comment by jenstornell** [comment]
@bnomei I think it's not in line in how the other hooks are named and that's why I have a problem with it. The current pattern is lowercase strings and dots between them.

This would follow that convention, in a way:

```php
panel.page.before.delete
```

But if it's `panel.[type].[action]` then it's not correct. Then it would be more like this:

```php
panel.page.delete.before
```

Then it would be `panel.[type].[action].[when]`. The last one should therefor be a good one?

@bnomei,  you just learned me that there is a thumb down. You got one back at ya. ;)

**Comment by texnixe** [comment]
> You got one back at ya. ;)

No kindergarten games, please.

**Comment by bnomei** [comment]
i use thumbs to invite others to poll-like feedback about solutions. since this did not seem to work well i removed them from this post. for me this thread is stalling and the devs should decide if and what to make of it.
