### ISSUE TITLE
Make content file operations thread-safe

### ISSUE THREAD

**Issue by kanni** [getkirby-v2/kirby#651]
So I built a small like plugin, utilising a route "/like" on my article pages and $page->increment(), I didn't bother implementing barriers on how often a user can like a post, if someone decides to spam the button, that's fine by me. A reader decided to write a shell script to see how often he could like one of my blogposts. After a couple of hundred of likes the .txt file for the article was wiped, except for the "Likes" field.

I can only imagine there's some kind of race condition going on ?!

I'll implement checks on how often/rapid a user can like, but maybe this is worth taking a look at cause it could potentially be dangerous? Or am I at fault for carelessly giving my users a way to call increment()?

Plugin code:
```
function increment_like($page_uri){
	$site = site();
	$page = $site->find($page_uri);
	$page->increment('likes')
	return $page->likes()->value();
}


kirby()->routes(array(  
	array(
		'pattern' => '(:any)/like',
		'method'  => 'GET',
		'action'  => function($uri) {
			$resp = increment_like($uri);
			die(json_encode($resp));
		}
	)
));
```

**Comment by lukasbestle** [comment]
It's definitely not your fault that this happens.

The Kirby content files are not [thread-safe](https://en.wikipedia.org/wiki/Thread_safety), which means that if multiple PHP threads try to access the same content file at the same time, it can happen that:

- process 1 writes to the file (which wipes it for a very short amount of time),
- process 2 tries to read the now empty file,
- process 1 finishes writing,
- process 2 writes to the file based on its incomplete memory representation of the file (which only writes the one field you were incrementing).

The only way to prevent that is locking. We do that for our session files in Kirby 3 because security is very important there. The issue with locking is the slightly reduced performance and added complexity. So it's a difficult question whether we should implement locking for the content files. @bastianallgeier?
