### ISSUE TITLE
Cross-site scripting exploit

### ISSUE THREAD

**Issue by anvart** [getkirby-v2/kirby#666]
Anybody heard of this problem: https://www.exploit-db.com/exploits/45068?

It was reported quite a while ago, but I googled and found nothing about fixes.

**Comment by bastianallgeier** [comment]
Yes, we heard about this problem and discussed internally back then that we don't consider it a direct security issue. The described attack only works when you inject malicious code as a panel editor. This is a scenario that is pretty theoretical in our opinion because panel editors can do much worse things than that if they can't be trusted in the first place. (deleting pages, changing content, uploading porn etc.) 

If you still want to fully mitigate this risk you need to escape all kind of content that would come from the cms. Any page field, site field or file field used in the template.

**Comment by anvart** [comment]
Thank your for your quick and comprehensive reply. What you're saying makes complete sence and I have no more questions. 

Closing the issue.

P.s.
Sad to hear about that unsuccessful dialogue.
